# name: 단위 테스트 / 앱 빌드
# on:
#   issue_comment:
#     types: [ created ]
# jobs:
#   build-app:
#     runs-on: ubuntu-latest
#     if: ${{ contains(github.event.comment.body, '@tester-prnd build') }}
#     steps:
#       - uses: octokit/request-action@v2.0.0
#         with:
#           route: ${{ github.event.issue.pull_request.url }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: echo "PR URL is ${{ github.event.issue.pull_request.url }}"

name: Check run
on:
  push:
    branches:
      - main
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: olaf-prnd
          repo: workflow-test
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Download file
      - uses: octokit/request-action@v2.x
        id: download_file
        with:
          route: GET /repos/OWNER/REPO/contents/README.md
          owner: olaf-prnd
          repo: workflow-test
          mediaType: | # The | is significant!
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Update check run to completed, successful status
      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: olaf-prnd
          repo: workflow-test
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
