name: Release PR 생성
on:
  workflow_dispatch:
    inputs:
      jira_version_prefix:
        required: true
        type: string
      main_branch_name:
        type: string
        default: "main"
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Release PR 생성 (main)
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ inputs.main_branch_name }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pr_assignee: ${{ github.event.head_commit.author.name }}
          pr_title: "dummy title (main)"
          pr_body: "dummy body"
          pr_draft: ${{ inputs.main_branch_name == 'hotfix' }}
      - name: Release PR 생성 (develop)
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pr_assignee: ${{ github.event.head_commit.author.name }}
          pr_title: "dummy title (develop)"
          pr_body: "${{steps.create_pr.outputs.pr_url}}"
          pr_draft: ${{ inputs.main_branch_name == 'hotfix' }}
