name: 테스트
on:
  workflow_dispatch:
    inputs:
      main_branch_name:
        type: string
        default: "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: variable 체크
        if: ${{ fromJSON(vars.STAGED_ROLLOUT_ENABLED) }}
        run: echo ${{ vars.IS_ENABLED }}
      - name: workflow 종료
        run: ls
